### ISSUE TITLE
Floating Point Value comparison

### ISSUE THREAD

**Issue by soneryaldiz** [intel/rohd-hcl#114]
### Describe the bug

Comparison of floating point values should take sign into consideration. 

### To Reproduce

```dart
fp = FloatingPointValue.ofSeparatedBinaryStrings('1 0101 0101');
expect(fp.compareTo(FloatingPointValue.ofSeparatedBinaryStrings('1 0101 0101')), 0);
expect(fp.compareTo(FloatingPointValue.ofSeparatedBinaryStrings('1 0100 0101')), lessThan(0));
expect(fp.compareTo(FloatingPointValue.ofSeparatedBinaryStrings('1 0101 0100')), lessThan(0));
```

**Comment by desmonddak** [comment]
I am not following this test.  On the second test, we  have fp.exponent = 5 and the new constructed fp has exponent =4.  So compare should be greateTthan(0) not lessThan(0).

I am fixing the comparison to also not differentiate between +0 and -0.

**Comment by soneryaldiz** [comment]
Test 2 compares -2^(5-bias) to -2^(4-bias) and the result should be less than zero as the former number is smaller than the latter.

**Comment by desmonddak** [comment]
#131 fixes this bug.
