### ISSUE TITLE
Derived FloatingPointValue ofInts Function Crashes

### ISSUE THREAD

**Issue by kimmeljo** [intel/rohd-hcl#124]
### Describe the bug

ofInts function for derived FloatingPointValue objects (ex: FloatingPoint16Value) crashes when invoked (in all cases). This is because it does not pass valid exponent and mantissa widths to the super constructor which consequently takes them to be 0. 

### To Reproduce

`final tmp = FloatingPoint16Value.ofInts(15, 0);`

### Expected behavior

Function call is successful and returns the corresponding FloatingPointValue derived type assuming the inputs are valid (i.e., within the integer bounds of the exponent and mantissa respectively).

### Actual behavior

ROHD HCL exception due to bad exponent/mantissa widths.

**Comment by desmonddak** [comment]
Fixed with PR #126
