### ISSUE TITLE
Binary Counter

### ISSUE THREAD

**Issue by mkorbel1** [intel/rohd-hcl#73]
### Motivation

Configurable counters are useful!

### Desired solution

- Reset with reset value
- Saturation value (maximum value)
- Saturation behavior (overflow vs. hold at saturated value)
- Enable (increment) -> when high: increment, when low: don't increment
- Enable decrement
- Increment amount
- Decrement amount
- number of increments/decrements (different constructors maybe for 1 vs multiple)

**Comment by RPG-coder-intc** [comment]
Hey Max! I will work on this one

**Comment by mkorbel1** [comment]
In consideration for up counters and down counters, does saturation count as only == saturation value, or is it >= or <= in case incr/decr amount is not 1?
